responses_financial_markets = [
    [
        {
            "query": "financial markets",
            "position": 1,
            "title": "Can the Integration of Capital Markets Spur Regional Economic Growth?",
            "body": "American development has been characterized by large movements of capital and labor headed to the economic frontier in search of higher returns.",
            "posted": "1 day ago",
            "source": "Harvard Joint Center for Housing Studies",
            "link": "https: //www.jchs.harvard.edu/blog/can-integration-capital-markets-spur-regional-economic-growth",
        },
        {
            "query": "financial markets",
            "position": 2,
            "title": "Project Pine: Central Bank Open Market Operations With Smart Contracts",
            "body": "Project Pine explored if and how central banks could continue to implement monetary policy operations in hypothetical tokenized wholesale financial markets.",
            "posted": "1 day ago",
            "source": "Federal Reserve Bank of New York",
            "link": "https://www.newyorkfed.org/aboutthefed/nyic/project-pine",
        },
        {
            "query": "financial markets",
            "position": 3,
            "title": "Financial markets embrace the tariff pause",
            "body": "Risk appetite recovers, following the spike in volatility at the beginning of April. However, the divergence between the central banks' strategies is...",
            "posted": "6 hours ago",
            "source": "CaixaBank Research",
            "link": "https://www.caixabankresearch.com/en/economics-markets/financial-markets/financial-markets-embrace-tariff-pause",
        },
        {
            "query": "financial markets",
            "position": 4,
            "title": "Weekly market commentary",
            "body": "Stay tuned for insights on hot topics and latest trends in the financial market via the Weekly commentary by the BlackRock Investment Institute.",
            "posted": "2 days ago",
            "source": "BlackRock",
            "link": "https://www.blackrock.com/corporate/insights/blackrock-investment-institute/publications/weekly-commentary",
        },
        {
            "query": "financial markets",
            "position": 5,
            "title": "April capital markets roundup: Volatility, notable deals, regulatory updates",
            "body": "April was marked by significant volatility, driven by U.S. tariffs on trading partners. Last month also saw a few key mergers and acquisitions,...",
            "posted": "2 days ago",
            "source": "The Real Economy Blog",
            "link": "https://realeconomy.rsmus.com/april-capital-markets-roundup-volatility-notable-deals-regulatory-updates/",
        },
        {
            "query": "financial markets",
            "position": 6,
            "title": "Weekly market wrap",
            "body": "Stocks post gains as trade tensions ease further · U.S. reaches trade deal with U.K. and agrees to talks with China · Fed holds rates steady, flagging labor...",
            "posted": "5 days ago",
            "source": "Edward Jones",
            "link": "https://www.edwardjones.ca/ca-en/market-news-insights/stock-market-news/stock-market-weekly-update",
        },
        {
            "query": "financial markets",
            "position": 7,
            "title": "Big news missing the big picture: Stock market performance in the news",
            "body": "The performance of stock markets often appears worse in the daily news than it actually is. This column argues that this negative news bias arises from two...",
            "posted": "4 days ago",
            "source": "CEPR",
            "link": "https://cepr.org/voxeu/columns/big-news-missing-big-picture-stock-market-performance-news",
        },
        {
            "query": "financial markets",
            "position": 8,
            "title": "Global Times: China's financial markets show strong resilience; nation has ample policy room to tackle external challenges: expert",
            "body": "BEIJING, May 12, 2025 /PRNewswire/ -- China's financial markets have held steady, with the benchmark Shanghai Composite Index rising back above 3,300 in May...",
            "posted": "3 days ago",
            "source": "WJBF",
            "link": "https://www.wjbf.com/business/press-releases/cision/20250512CN85422/global-times-chinas-financial-markets-show-strong-resilience-nation-has-ample-policy-room-to-tackle-external-challenges-expert",
        },
        {
            "query": "financial markets",
            "position": 9,
            "title": "Dow jumps more than 1,100 points, S&P 500 rises 3% on China-U.S. temporary tariff cut: Live updates",
            "body": "U.S. stocks rallied Monday after the U.S. and China agreed to temporarily slash tariffs following negotiations over the weekend in Switzerland.",
            "posted": "2 days ago",
            "source": "CNBC",
            "link": "https://www.cnbc.com/2025/05/11/stock-market-today-live-updates.html",
        },
        {
            "query": "financial markets",
            "position": 10,
            "title": "PHOTO COLLECTION: Financial Markets Global",
            "body": "Traders Michael Capolino, left, and Robert Charmak work on the floor of the New York Stock Exchange, Monday, May 12, 2025. Richard Drew/AP.",
            "posted": "2 days ago",
            "source": "Big Rapids Pioneer",
            "link": "https://www.bigrapidsnews.com/news/article/photo-collection-financial-markets-global-20316430.php",
        },
        {
            "query": "financial markets",
            "position": 11,
            "title": "Should I Pull All Of My Money Out of the Stock Market Now?",
            "body": "Fight the urge to panic-sell into volatile markets, as long-term trends suggest that bear markets always eventually recover.",
            "posted": "5 days ago",
            "source": "Investopedia",
            "link": "https://www.investopedia.com/should-i-get-out-of-the-stock-market-now-11721856",
        },
        {
            "query": "financial markets",
            "position": 12,
            "title": "Stocks Rally as U.S. and China Pull Back on Tariffs",
            "body": "The S&P 500 logged its biggest gain in over a month after American and Chinese officials signaled a de-escalation in the trade war between the world's two...",
            "posted": "3 days ago",
            "source": "The New York Times",
            "link": "https://www.nytimes.com/2025/05/11/business/us-china-trade-stock-market.html",
        },
        {
            "query": "financial markets",
            "position": 13,
            "title": "PHOTO COLLECTION: Financial Markets Global",
            "body": "Traders Michael Capolino, left, and Robert Charmak work on the floor of the New York Stock Exchange, Monday, May 12, 2025. Richard Drew/AP.",
            "posted": "3 days ago",
            "source": "Big Rapids Pioneer",
            "link": "https://www.bigrapidsnews.com/news/article/photo-collection-financial-markets-global-20316430.php",
        },
        {
            "query": "financial markets",
            "position": 14,
            "title": "PHOTO COLLECTION: Financial markets",
            "body": "Trader Niall Pawa, left, and specialist Meric Greenberg work on the floor of the New York Stock Exchange, Monday, May 12, 2025. Richard Drew/AP.",
            "posted": "3 days ago",
            "source": "The Edwardsville Intelligencer",
            "link": "https://www.theintelligencer.com/news/article/photo-collection-financial-markets-20322844.php",
        },
        {
            "query": "financial markets",
            "position": 15,
            "title": "Most Gulf stock markets extend gains after US-China trade agreement",
            "body": "Gulf stock markets continued their upward trend early on Monday, buoyed by rising oil prices and developments in U.S.-China trade negotiations,...",
            "posted": "3 days ago",
            "source": "Reuters",
            "link": "https://www.reuters.com/world/middle-east/most-gulf-stock-markets-extend-gains-after-us-china-trade-agreement-2025-05-12/",
        },
        {
            "query": "financial markets",
            "position": 16,
            "title": "These Global ETFs Beat U.S. Even After Monday's Rally; Where To Find The Biggest Returns",
            "body": "Despite tariffs, many ETFs that track world markets are up more than 20% this year — and one is up 42%. Why international stocks are climbing.",
            "posted": "2 days ago",
            "source": "Investor's Business Daily",
            "link": "https://www.investors.com/news/world-markets-stocks-tariffs/",
        },
        {
            "query": "financial markets",
            "position": 17,
            "title": "The Stock Market’s Boomerang Month Has Put Investors in a Bind",
            "body": "The stock market is now higher than before President Trump's broad and steep tariffs sent share prices into a tailspin. The 10-year government bond yield is...",
            "posted": "1 day ago",
            "source": "The New York Times",
            "link": "https://www.nytimes.com/2025/05/13/business/stock-market-trump-tariffs.html",
        },
        {
            "query": "financial markets",
            "position": 18,
            "title": "Morning Bid: Trade peace in our time, or just 90 more days?",
            "body": "What matters in U.S. and global markets today.",
            "posted": "3 days ago",
            "source": "Reuters",
            "link": "https://www.reuters.com/markets/us/global-markets-view-usa-2025-05-12/",
        },
        {
            "query": "financial markets",
            "position": 19,
            "title": "Stock Market Today: Stock Market News And Analysis",
            "body": "The Stock Market Today column highlights the latest stock market news and alerts you to any changes in market trend. You'll also get ongoing analysis of the...",
            "posted": "22 hours ago",
            "source": "Investor's Business Daily",
            "link": "https://www.investors.com/news/stock-market-today-stock-market-news/",
        },
        {
            "query": "financial markets",
            "position": 20,
            "title": "Hope and Anxiety Share the Stage as Finance Titans Converge on L.A.",
            "body": "At the Milken Institute conference, a who's who of finance and corporate America, there was a mix of emotions about financial markets and the economy.",
            "posted": "6 days ago",
            "source": "The New York Times",
            "link": "https://www.nytimes.com/2025/05/08/business/milken-tariffs-economy.html",
        },
        {
            "query": "financial markets",
            "position": 21,
            "title": "Financial Markets On The Rise With Stocks, Bitcoin, And Trades",
            "body": "What's going on here? A wave of bullishness has hit financial markets: US and UK stocks are on the rise, bitcoin reaches new highs, and a pivotal trade deal...",
            "posted": "6 days ago",
            "source": "Finimize",
            "link": "https://finimize.com/content/financial-markets-on-the-rise-with-stocks-bitcoin-and-trades",
        },
        {
            "query": "financial markets",
            "position": 22,
            "title": "Fact Sheets: Policymakers Must Bolster The Treasury Market and Weakening Bank Capital Will Not Help the Treasury Market but Will Increase Financial Stability Risks",
            "body": "WASHINGTON, D.C.—Ben Schiffrin and Phillip Basil, Directors of Securities Policy and Economic Growth & Financial Stability, issued the following statement...",
            "posted": "24 hours ago",
            "source": "Better Markets",
            "link": "https://bettermarkets.org/newsroom/fact-sheets-policymakers-must-bolster-the-treasury-market-and-weakening-bank-capital-will-not-help-the-treasury-market-but-will-increase-financial-stability-risks/",
        },
        {
            "query": "financial markets",
            "position": 23,
            "title": "Create Your Calm with 'Financial Essentials' Primer",
            "body": "Are you avoiding your retirement account right now? With the uncertainty of the worldwide financial environment, it's understandable if you are.",
            "posted": "6 days ago",
            "source": "Human Resources University of Michigan |",
            "link": "https://hr.umich.edu/about-uhr/uhr-news/create-your-calm-financial-essentials-primer",
        },
        {
            "query": "financial markets",
            "position": 24,
            "title": "Global Financial Markets Rebound As FTSE Mondo Visione Index Hits Record High In April",
            "body": "April 2025 marked a month of volatility and recovery, with the FTSE Mondo Visione Index achieving an all-time closing high. Global financial markets began...",
            "posted": "3 days ago",
            "source": "Mondo Visione",
            "link": "https://mondovisione.com/media-and-resources/press/press-releases/global-financial-markets-rebound-as-ftse-mondo-visione-index-hits-record-high-in/",
        },
        {
            "query": "financial markets",
            "position": 25,
            "title": "IPC Partners with Open Lake Technology to transform communications compliance assurance in financial markets",
            "body": "New York, London, May 13, 2025 (GLOBE NEWSWIRE) -- IPC, a leading global provider of secure, compliant communications and multi-cloud connectivity...",
            "posted": "2 days ago",
            "source": "GlobeNewswire",
            "link": "https://www.globenewswire.com/news-release/2025/05/13/3079785/0/en/IPC-Partners-with-Open-Lake-Technology-to-transform-communications-compliance-assurance-in-financial-markets.html",
        },
        {
            "query": "financial markets",
            "position": 26,
            "title": "Can Europe finally fix its capital markets?",
            "body": "Stung by its lack of competitiveness, the EU is making a new push to create a deep financial market. Some investors believe this time could be different.",
            "posted": "2 days ago",
            "source": "Financial Times",
            "link": "https://www.ft.com/content/e23117c0-3fe6-4b89-b1fc-c99f49976dc0",
        },
        {
            "query": "financial markets",
            "position": 27,
            "title": "PitchBook Strengthens Leadership in Global Capital Market Data Coverage",
            "body": "PitchBook, the premier data provider for the private and public equity and credit markets, has released its bi-annual snapshot of data coverage across the...",
            "posted": "6 days ago",
            "source": "Business Wire",
            "link": "https://www.businesswire.com/news/home/20250508033358/en/PitchBook-Strengthens-Leadership-in-Global-Capital-Market-Data-Coverage",
        },
        {
            "query": "financial markets",
            "position": 28,
            "title": "How the Debt Ceiling Is Now Pouring Liquidity into Financial Markets, only to Suck it Back Out Very Fast Later this Year",
            "body": "Last time, $840 billion got sucked out in 5 months, all from excess cash in ON RRPs. But after $2.26 trillion of QT, ON RRPs are nearly gone.",
            "posted": "3 days ago",
            "source": "Wolf Street",
            "link": "https://wolfstreet.com/2025/05/11/how-the-debt-ceiling-is-now-pouring-liquidity-into-financial-markets-only-to-suck-it-back-out-very-fast-later-this-year/",
        },
        {
            "query": "financial markets",
            "position": 29,
            "title": "What’s Happening in the Markets This Week",
            "body": "CPI report to be released.",
            "posted": "5 days ago",
            "source": "Morningstar",
            "link": "https://www.morningstar.com/markets/whats-happening-markets-this-week",
        },
        {
            "query": "financial markets",
            "position": 30,
            "title": "Dennis Kelleher, CEO of Better Markets, Named to Washingtonian’s 500 Most Influential List For 5th Year in a Row",
            "body": "WASHINGTON, D.C.— For the fifth year in a row, Washingtonian Magazine has selected Dennis Kelleher, Co-Founder, President and CEO of Better Markets,...",
            "posted": "6 days ago",
            "source": "Better Markets",
            "link": "https://bettermarkets.org/newsroom/dennis-kelleher-ceo-of-better-markets-named-to-washingtonians-500-most-influential-list-for-5th-year-in-a-row/",
        },
    ]
]

responses_market_volatlity = [
    [
        {
            "query": "financial markets",
            "position": 1,
            "title": "Can the Integration of Capital Markets Spur Regional Economic Growth?",
            "body": "American development has been characterized by large movements of capital and labor headed to the economic frontier in search of higher returns.",
            "posted": "1 day ago",
            "source": "Harvard Joint Center for Housing Studies",
            "link": "https://www.jchs.harvard.edu/blog/can-integration-capital-markets-spur-regional-economic-growth",
        },
        {
            "query": "financial markets",
            "position": 2,
            "title": "Project Pine: Central Bank Open Market Operations With Smart Contracts",
            "body": "Project Pine explored if and how central banks could continue to implement monetary policy operations in hypothetical tokenized wholesale financial markets.",
            "posted": "1 day ago",
            "source": "Federal Reserve Bank of New York",
            "link": "https://www.newyorkfed.org/aboutthefed/nyic/project-pine",
        },
        {
            "query": "financial markets",
            "position": 3,
            "title": "Financial markets embrace the tariff pause",
            "body": "Risk appetite recovers, following the spike in volatility at the beginning of April. However, the divergence between the central banks' strategies is...",
            "posted": "6 hours ago",
            "source": "CaixaBank Research",
            "link": "https://www.caixabankresearch.com/en/economics-markets/financial-markets/financial-markets-embrace-tariff-pause",
        },
        {
            "query": "financial markets",
            "position": 4,
            "title": "Weekly market commentary",
            "body": "Stay tuned for insights on hot topics and latest trends in the financial market via the Weekly commentary by the BlackRock Investment Institute.",
            "posted": "2 days ago",
            "source": "BlackRock",
            "link": "https://www.blackrock.com/corporate/insights/blackrock-investment-institute/publications/weekly-commentary",
        },
        {
            "query": "financial markets",
            "position": 5,
            "title": "April capital markets roundup: Volatility, notable deals, regulatory updates",
            "body": "April was marked by significant volatility, driven by U.S. tariffs on trading partners. Last month also saw a few key mergers and acquisitions,...",
            "posted": "2 days ago",
            "source": "The Real Economy Blog",
            "link": "https://realeconomy.rsmus.com/april-capital-markets-roundup-volatility-notable-deals-regulatory-updates/",
        },
        {
            "query": "financial markets",
            "position": 6,
            "title": "Weekly market wrap",
            "body": "Stocks post gains as trade tensions ease further · U.S. reaches trade deal with U.K. and agrees to talks with China · Fed holds rates steady, flagging labor...",
            "posted": "5 days ago",
            "source": "Edward Jones",
            "link": "https://www.edwardjones.ca/ca-en/market-news-insights/stock-market-news/stock-market-weekly-update",
        },
        {
            "query": "financial markets",
            "position": 7,
            "title": "Big news missing the big picture: Stock market performance in the news",
            "body": "The performance of stock markets often appears worse in the daily news than it actually is. This column argues that this negative news bias arises from two...",
            "posted": "4 days ago",
            "source": "CEPR",
            "link": "https://cepr.org/voxeu/columns/big-news-missing-big-picture-stock-market-performance-news",
        },
        {
            "query": "financial markets",
            "position": 8,
            "title": "Global Times: China's financial markets show strong resilience; nation has ample policy room to tackle external challenges: expert",
            "body": "BEIJING, May 12, 2025 /PRNewswire/ -- China's financial markets have held steady, with the benchmark Shanghai Composite Index rising back above 3,300 in May...",
            "posted": "3 days ago",
            "source": "WJBF",
            "link": "https://www.wjbf.com/business/press-releases/cision/20250512CN85422/global-times-chinas-financial-markets-show-strong-resilience-nation-has-ample-policy-room-to-tackle-external-challenges-expert",
        },
        {
            "query": "financial markets",
            "position": 9,
            "title": "Dow jumps more than 1,100 points, S&P 500 rises 3% on China-U.S. temporary tariff cut: Live updates",
            "body": "U.S. stocks rallied Monday after the U.S. and China agreed to temporarily slash tariffs following negotiations over the weekend in Switzerland.",
            "posted": "2 days ago",
            "source": "CNBC",
            "link": "https://www.cnbc.com/2025/05/11/stock-market-today-live-updates.html",
        },
        {
            "query": "financial markets",
            "position": 10,
            "title": "PHOTO COLLECTION: Financial Markets Global",
            "body": "Traders Michael Capolino, left, and Robert Charmak work on the floor of the New York Stock Exchange, Monday, May 12, 2025. Richard Drew/AP.",
            "posted": "2 days ago",
            "source": "Big Rapids Pioneer",
            "link": "https://www.bigrapidsnews.com/news/article/photo-collection-financial-markets-global-20316430.php",
        },
    ]
]
responses_emergin_markets = [
    [
        {
            "query": "emerging markets",
            "position": 1,
            "title": "Emerging markets confront a trade dilemma",
            "body": "The implicit message from the U.S. and China, the world's leading economies, is that emerging markets should decide which side to back.",
            "posted": "2 days ago",
            "source": "The Berkshire Eagle",
            "link": "https://www.berkshireeagle.com/business/columnist/emerging-markets-confront-trade-dilemma/article_bdf42bff-91c9-492c-86b2-55029fe84efc.html",
        },
        {
            "query": "emerging markets",
            "position": 2,
            "title": "Emerging Markets Report: A Milestone for Mycelium",
            "body": "Underreported D.E.A. Letter and Policy Position Could be a Game Changer for Mushroom Enthusiasts An Emerging Markets Sponsored Commentary ORLANDO, Fla.,...",
            "posted": "3 days ago",
            "source": "GlobeNewswire",
            "link": "https://www.globenewswire.com/news-release/2025/05/12/3079006/0/en/Emerging-Markets-Report-A-Milestone-for-Mycelium.html",
        },
        {
            "query": "emerging markets",
            "position": 3,
            "title": "Harbor Capital Advisors Expands Growing ETF Lineup with the Harbor Emerging Markets Select ETF and Extends Partnership with C WorldWide Asset Management",
            "body": 'Harbor Capital Advisors, Inc. ("Harbor"), an asset manager that curates a suite of actively managed ETFs, collective investment trusts, and mutual funds is...',
            "posted": "3 hours ago",
            "source": "Business Wire",
            "link": "https://www.businesswire.com/news/home/20250515839089/en/Harbor-Capital-Advisors-Expands-Growing-ETF-Lineup-with-the-Harbor-Emerging-Markets-Select-ETF-and-Extends-Partnership-with-C-WorldWide-Asset-Management",
        },
        {
            "query": "emerging markets",
            "position": 4,
            "title": "Emerging markets take a hit from tariffs",
            "body": "Alongside weaker global growth, emerging markets are highly exposed to a host of negative impacts from a trade war, says Fitch Ratings. In a new report,...",
            "posted": "6 days ago",
            "source": "Investment Executive",
            "link": "https://www.investmentexecutive.com/news/research-and-markets/emerging-markets-take-a-hit-from-tariffs/",
        },
        {
            "query": "emerging markets",
            "position": 5,
            "title": "India and China Take a Popular Fund on a Wild Ride",
            "body": "GQG's emerging-markets fund feels the impact of its bold bets.",
            "posted": "1 day ago",
            "source": "Morningstar",
            "link": "https://www.morningstar.com/funds/india-china-take-popular-fund-wild-ride",
        },
        {
            "query": "emerging markets",
            "position": 6,
            "title": "Three Archetypes To Fintech Success In Latam (and Emerging Markets)",
            "body": "How do latam fintech companies scale? How do they navigate a fragmented, highly regulated, and deeply local landscape? Three archetypes emerge.",
            "posted": "1 day ago",
            "source": "Forbes",
            "link": "https://www.forbes.com/sites/alexlazarow/2025/05/14/the-three-archetypes-to-fintech-success-in-latam--emerging-markets/",
        },
        {
            "query": "emerging markets",
            "position": 7,
            "title": "Why emerging markets are a 'key area' for diversification",
            "body": "Emerging markets may offer investors overlooked opportunities as market uncertainty rises. Malcolm Dorson, Global X senior portfolio manager and head of...",
            "posted": "1 day ago",
            "source": "Yahoo Finance",
            "link": "https://finance.yahoo.com/video/why-emerging-markets-key-area-110004870.html",
        },
        {
            "query": "emerging markets",
            "position": 8,
            "title": "Ten Questions Boards in Emerging Economies Must Ask",
            "body": "Geopolitical and trade uncertainty, regulatory shifts, rapidly evolving artificial intelligence development and extreme weather disruptions are the...",
            "posted": "15 hours ago",
            "source": "INSEAD Knowledge",
            "link": "https://knowledge.insead.edu/leadership-organisations/ten-questions-boards-emerging-economies-must-ask",
        },
        {
            "query": "emerging markets",
            "position": 9,
            "title": "Regulators in emerging markets should consider alternative data for credit scoring",
            "body": "Indermit Gill is the chief economist of the World Bank Group and Sophie Sirtaine is the CEO of CGAP. For decades, traditional models of lending that relied...",
            "posted": "3 days ago",
            "source": "TheBanker.com",
            "link": "https://www.thebanker.com/content/ac23a134-eac5-4a7b-8e0b-4d2191b149fa",
        },
        {
            "query": "emerging markets",
            "position": 10,
            "title": "Payment partnership targets emerging markets",
            "body": "dLocal, a cross-border payment platform for emerging markets, has announced what it calls an expanded relationship with financial technology company PayPal...",
            "posted": "6 days ago",
            "source": "Developing Telecoms",
            "link": "https://developingtelecoms.com/telecom-technology/enterprise-ecosystems/18456-payment-partnership-targets-emerging-markets.html",
        },
        {
            "query": "emerging markets",
            "position": 11,
            "title": "Payment partnership targets emerging markets",
            "body": "dLocal, a cross-border payment platform for emerging markets, has announced what it calls an expanded relationship with financial technology company PayPal...",
            "posted": "6 days ago",
            "source": "Developing Telecoms",
            "link": "https://developingtelecoms.com/telecom-technology/enterprise-ecosystems/18456-payment-partnership-targets-emerging-markets.html",
        },
        {
            "query": "emerging markets",
            "position": 12,
            "title": "Is DFA Emerging Markets Core Equity I (DFCEX) a Strong Mutual Fund Pick Right Now?",
            "body": "Having trouble finding a Non US - Equity fund? DFA Emerging Markets Core Equity I (DFCEX) is a potential starting point. DFCEX holds a Zacks Mutual Fund...",
            "posted": "1 day ago",
            "source": "Nasdaq",
            "link": "https://www.nasdaq.com/articles/dfa-emerging-markets-core-equity-i-dfcex-strong-mutual-fund-pick-right-now-0",
        },
        {
            "query": "emerging markets",
            "position": 13,
            "title": "Chinese Vaccine Makers Turn To Emerging Markets",
            "body": "Chinese producers of novel vaccines are increasingly pivoting to developing markets overseas in the face of a collapse in their domestic sales.",
            "posted": "6 days ago",
            "source": "insights.citeline.com",
            "link": "https://insights.citeline.com/scrip/focus-on-asia/china/chinese-vaccine-makers-turn-to-emerging-markets-MXKNEVPC75CIRIXXRBFMTRVGOQ/",
        },
        {
            "query": "emerging markets",
            "position": 14,
            "title": "SCHE: Rotation Away From U.S. Assets Could Favor Emerging Markets",
            "body": "Schwab Emerging Markets Equity ETF benefits from a weaker U.S. dollar and relatively stable commodity prices. See why SCHE is a Buy.",
            "posted": "3 days ago",
            "source": "Seeking Alpha",
            "link": "https://seekingalpha.com/article/4785453-sche-rotation-away-from-us-assets-could-favor-emerging-markets",
        },
        {
            "query": "emerging markets",
            "position": 15,
            "title": "Bloomberg’s Butler moves to emerging markets team",
            "body": "Bloomberg News reporter Kelsey Butler has moved to the emerging markets team with a focus on Mexico. Kelsey Butler. She has been an equality reporter and...",
            "posted": "1 day ago",
            "source": "Talking Biz News",
            "link": "https://talkingbiznews.com/media-news/bloombergs-butler-moves-to-emerging-markets-team/",
        },
        {
            "query": "emerging markets",
            "position": 16,
            "title": "Cost-Benefit Analysis of AI-Driven Cancer Prediction Models in Emerging Markets: Insights from Guru Lakshmi Priyanka Bodagala",
            "body": "Understanding the practical implications, ethical considerations, and future trajectory of AI in oncology within these specific contexts is crucial for...",
            "posted": "2 days ago",
            "source": "Tech Times",
            "link": "https://www.techtimes.com/articles/310312/20250513/cost-benefit-analysis-ai-driven-cancer-prediction-models-emerging-markets-insights-guru-lakshmi.htm",
        },
        {
            "query": "emerging markets",
            "position": 17,
            "title": "IMF 2025 Spring Takeaways: The Era of EM Exceptionalism",
            "body": "At the Spring IMF meetings, our EM Debt team saw stronger investor sentiment as EMs benefit from dollar weakness, stable inflation, and growing confidence...",
            "posted": "3 days ago",
            "source": "VanEck",
            "link": "https://www.vaneck.com/us/en/blogs/emerging-markets-bonds/imf-2025-spring-takeaways-the-era-of-em-exceptionalism/",
        },
        {
            "query": "emerging markets",
            "position": 18,
            "title": "Is WisdomTree Emerging Markets High Dividend ETF (DEM) a Strong ETF Right Now?",
            "body": "Launched on 07/13/2007, the WisdomTree Emerging Markets High Dividend ETF (DEM) is a smart beta exchange traded fund offering broad exposure to the Broad...",
            "posted": "2 days ago",
            "source": "Yahoo Finance",
            "link": "https://finance.yahoo.com/news/wisdomtree-emerging-markets-high-dividend-102005765.html",
        },
        {
            "query": "emerging markets",
            "position": 19,
            "title": "Invesco Emerging Markets Local Debt Fund Q1 2025 Commentary",
            "body": "Emerging market local bonds, in our view, offer an attractive opportunity to invest in a high-yielding asset class with low correlation to both US stocks...",
            "posted": "3 days ago",
            "source": "Seeking Alpha",
            "link": "https://seekingalpha.com/article/4785351-invesco-emerging-markets-local-debt-fund-q1-2025-commentary",
        },
        {
            "query": "emerging markets",
            "position": 20,
            "title": "Egg prices, buying a car, emerging market investments: Wealth",
            "body": "On today's installment of Wealth, host Brad Smith speaks to several personal finance experts and business owners as the stock market (^DJI, ^IXIC,...",
            "posted": "1 day ago",
            "source": "Yahoo Finance",
            "link": "https://finance.yahoo.com/video/egg-prices-buying-car-emerging-165008542.html",
        },
    ]
]

responses_options_volatility = [
    [
        {
            "query": "options volatility",
            "position": 1,
            "title": "Implied Volatility Surging for Union Pacific Stock Options",
            "body": "Investors need to pay close attention to Union Pacific stock based on the movements in the options market lately.",
            "posted": "3 days ago",
            "source": "Yahoo Finance",
            "link": "https://finance.yahoo.com/news/implied-volatility-surging-union-pacific-141000994.html",
        },
        {
            "query": "options volatility",
            "position": 2,
            "title": "Mathematical Volatility Mean Reversion",
            "body": "content related to Mathematical Volatility Mean Reversion.",
            "posted": "3 days ago",
            "source": "tastylive",
            "link": "https://www.tastylive.com/shows/the-skinny-on-options-abstract-applications/episodes/mathematical-volatility-mean-reversion-05-12-2025",
        },
        {
            "query": "options volatility",
            "position": 3,
            "title": "Options Volatility and Implied Earnings Moves This Week, May 12 – May 15, 2025",
            "body": "This week, several major companies will be reporting earnings. Among them are Alibaba (BABA), Walmart (WMT), Plug Power (PLUG), Cisco Systems (CSCO),...",
            "posted": "3 days ago",
            "source": "TipRanks",
            "link": "https://www.tipranks.com/news/options-volatility-and-implied-earnings-moves-this-week-may-12-may-15-2025",
        },
        {
            "query": "options volatility",
            "position": 4,
            "title": "Implied Volatility Surging for UMB Financial (UMBF) Stock Options",
            "body": "Investors need to pay close attention to UMB Financial (UMBF) stock based on the movements in the options market lately.",
            "posted": "6 days ago",
            "source": "Zacks Investment Research",
            "link": "https://www.zacks.com/stock/news/2465477/implied-volatility-surging-for-umb-financial-umbf-stock-options",
        },
        {
            "query": "options volatility",
            "position": 5,
            "title": "Options Volatility and Implied Earnings Moves Today, May 12, 2025",
            "body": "Today, several major companies are expected to report earnings: 3D Systems (DDD), Petroleo Brasileiro SA- Petrobras (PBR), Plug Power (PLUG), Simon Property...",
            "posted": "3 days ago",
            "source": "TipRanks",
            "link": "https://www.tipranks.com/news/options-volatility-and-implied-earnings-moves-today-may-12-2025",
        },
        {
            "query": "options volatility",
            "position": 6,
            "title": "Options Volatility and Implied Earnings Moves Today, May 13, 2025",
            "body": "Today, several major companies are expected to report earnings: Exelixis (EXEL), Gevo (GEVO), Inovio Pharmaceuticals (INO), JD (JD), CyberArk Software...",
            "posted": "2 days ago",
            "source": "TipRanks",
            "link": "https://www.tipranks.com/news/options-volatility-and-implied-earnings-moves-today-may-13-2025",
        },
        {
            "query": "options volatility",
            "position": 7,
            "title": "Options Volatility and Implied Earnings Moves Today, May 15, 2025",
            "body": "Today, several major companies are expected to report earnings: Applied Materials (AMAT), Deere (DE), NetEase (NTES), Take-Two (TTWO), Walmart (WMT),...",
            "posted": "5 hours ago",
            "source": "TipRanks",
            "link": "https://www.tipranks.com/news/options-volatility-and-implied-earnings-moves-today-may-15-2025",
        },
        {
            "query": "options volatility",
            "position": 8,
            "title": "Options Volatility and Implied Earnings Moves Today, May 14, 2025",
            "body": "Today, several major companies are expected to report earnings: Cisco Systems (CSCO), Star Bulk Carriers (SBLK), Tower (TSEM), DXC Technology (DXC),...",
            "posted": "1 day ago",
            "source": "TipRanks",
            "link": "https://www.tipranks.com/news/options-volatility-and-implied-earnings-moves-today-may-14-2025",
        },
        {
            "query": "options volatility",
            "position": 9,
            "title": "Option Volatility And Earnings Report For May 12 - 16",
            "body": "Earnings season is winding down, but we do still have some big names reporting including Walmart, Alibaba, jd.com, Cisco and Deere & Company.",
            "posted": "3 days ago",
            "source": "Barchart.com",
            "link": "https://www.barchart.com/story/news/32342827/option-volatility-and-earnings-report-for-may-12-16",
        },
        {
            "query": "options volatility",
            "position": 10,
            "title": "Market volatility: Identifying and quantifying investment risks",
            "body": "Three common ways to measure volatility are beta, implied volatility, and the Cboe Volatility Index (VIX). Beta and VIX values can be found on most...",
            "posted": "2 days ago",
            "source": "Britannica",
            "link": "https://www.britannica.com/money/stock-market-volatility",
        },
    ]
]
